---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by hezhaoming.
--- DateTime: 2021/1/5 7:59 下午
---

local _M = {}

function _M.is_not_include(value, tab)
    if not tab then
        return true
    end
    for k, v in ipairs(tab) do
        if v == value then
            return false
        end
    end
    return true
end

--function test()
--
--    local arr = { "123", "456" }
--    local value = "12367"
--    local bool = _M.is_include(value, arr)
--    print(bool)
--
--end
--
--test()
return _M